### ISSUE TITLE
Plugin is not compatible with the version PhpStorm 2023.1

### ISSUE THREAD

**Issue by cuberinooo** [SolidWorx/idea-php-phake-plugin#3]
First of all thanks for creating the plugin !!! 
Will there be any chance to get this work on the latest PhpStorm version ?

**Comment by Guite** [comment]
Hi @pierredup 
thanks for your fast reaction.
Could you please submit the newest version to the JetBrains marketplace? Looking forward to give it a try :smile:

**Comment by pierredup** [comment]
@Guite it is already submitted to the marketplace, JetBrains takes a couple days to review and approve any new version, so hopefully it should be live by the weekend.
